version: "3"
services:
  db_dev:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: develop
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - "3308:3306"
    networks:
      - net_cms
    volumes:
      - db_cms_dev:/var/lib/mysql

volumes:
  db_cms_dev:

networks:
  net_cms:
